name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - run: npm ci
      - run: npm run build --if-present

      - name: Commit and push changes
        run: |
          git config user.name "Josh"
          git config user.email "josh@fitmatch.ai"
          git add dist/index.js
          git commit -m "Rebuild dist/index.js"
          git push origin HEAD:main
